inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
  TargetRubyVersion: 3.3.5
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
Layout/LineLength:
  Max: 188
