version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academic_performance_api_development
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  background_job:
    build: .
    command: bundle exec sidekiq
    environment:
      REDIS_URL: redis://redis:6379/1
      DATABASE_URL: postgresql://postgres:postgres@db/academic_performance_api_development
    depends_on:
      - redis
      - db
  web:
    build: .
    command: bash -c "bundle exec rails db:drop db:create db:migrate db:seed && bundle exec rails server -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/academic_performance_api_development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - db
      - redis
      - background_job
